# Changes here will be overwritten by Copier
# DO NOT MANUALLY MODIFY THIS FILE
_commit: latest
_src_path: https://github.com/calliope-project/data-module-template.git
author_email: j.a.c.launer@tudelft.nl
author_family_name: Launer
author_given_name: Jann
github_org: calliope-project
license: MIT
module_description: This data module produces capacity factors for PV and wind at
    arbitrary spatial resolution.
module_long_name: PV and wind capacity factors
module_short_name: module_pv_wind
