# Emulate a user configuring the module.
configfile: workflow.source_path("./test_config.yaml")


# Emulate how another workflow might create inputs for this module.
rule copy_external_input:
    message:
        "Example of a rule external to your module."
    input:
        layout_points="../files/layout_points_NLD.csv",
        layout_raster="../files/layout_raster_NLD.tif",
        shapes="../files/shapes_NLD.geojson",
        cutout="../files/era5.nc",
        tech_specs="../files/wind_onshore_3MW.yaml",
    output:
        layout_points="results/module_pv_wind/resources/user/layout/wind_onshore_point.csv",
        layout_raster="results/module_pv_wind/resources/user/layout/wind_onshore_raster.tif",
        shapes="results/module_pv_wind/resources/user/spatial_units/shapes_NLD.geojson",
        cutout="results/module_pv_wind/resources/user/cutout_era5-NLD.nc",
        tech_specs="results/module_pv_wind/resources/user/tech_specs/wind_onshore_3MW.yaml",
    shell:
        """
    cp {input.layout_points} {output.layout_points}
    cp {input.layout_raster} {output.layout_raster}
    cp {input.shapes} {output.shapes}
    cp {input.cutout} {output.cutout}
    cp {input.tech_specs} {output.tech_specs}
    """


# Import the module and configure it.
# `snakefile:` specifies the module. It can use file paths and special github(...) / gitlab(...) markers
# `prefix:` re-routes all input/output paths of the module, helping to avoid file conflicts.
module module_pv_wind:
    snakefile:
        "../../workflow/Snakefile"
    config:
        config["module_pv_wind_raster"]
    prefix:
        "results/module_pv_wind/"


# rename all module rules with a prefix, to avoid naming conflicts.
use rule * from module_pv_wind as module_pv_wind_*


# Request something from the module
rule all_raster:
    message:
        "A test case for your module."
    default_target: True
    input:
        "results/module_pv_wind/results/era5-NLD/shapes_NLD/wind_onshore_raster/capacityfactors_wind_onshore_3MW.nc",


module module_pv_wind:
    snakefile:
        "../../workflow/Snakefile"
    config:
        config["module_pv_wind_point"]
    prefix:
        "results/module_pv_wind/"


# rename all module rules with a prefix, to avoid naming conflicts.
use rule * from module_pv_wind as module_pv_wind_*


# Request something from the module
rule all_point:
    message:
        "A test case for your module."
    default_target: True
    input:
        "results/module_pv_wind/results/era5-NLD/shapes_NLD/wind_onshore_point/capacityfactors_wind_onshore_3MW.nc",
