# Emulate a user configuring the module.
configfile: workflow.source_path("./test_config.yaml")


# Import the module and configure it to use a point layout.
# `snakefile:` specifies the module. It can use file paths and special github(...) / gitlab(...) markers
# `prefix:` re-routes all input/output paths of the module, helping to avoid file conflicts.
module module_pv_wind_point:
    snakefile:
        "../../workflow/Snakefile"
    config:
        config["module_pv_wind_point"]


# rename all module rules with a prefix, to avoid naming conflicts.
use rule * from module_pv_wind_point as module_pv_wind_point_*


# Request something from the module
rule nld_point:
    message:
        "Create capacity factors for onshore wind based on a point layout."
    default_target: True
    input:
        "results/era5_2017/NLD_NUTS2_onshore/points_NLD/capacityfactors_wind_onshore_3MW.nc",
